/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.Random;

public class App {

    private static final String KNIGHT_NAME_PREFIX = "Knight_";
    private static final Random random = new Random();

    private static final int numberOfKnights = 3;
    private static final int initialHealth = 6;

    public static void main(String[] args) {

        Knight firstKnight = null;
        Knight previousKnight = null;
        for(int i=0; i<numberOfKnights; i++) {
            var knight = new Knight(KNIGHT_NAME_PREFIX + i, initialHealth);
            if (firstKnight == null) {
                firstKnight = knight;
            }
            if (previousKnight != null) {
                previousKnight.setNextKnight(knight);
            }
            previousKnight = knight;
        }
        previousKnight.setNextKnight(firstKnight);

        var attackingKnight = firstKnight;
        while (attackingKnight.getNextKnight() != attackingKnight) {
            int randomNumber = random.nextInt(6) + 1;
            System.out.println(attackingKnight + " deals " + randomNumber + " damage to " + attackingKnight.getNextKnight());
            attackingKnight.getNextKnight().receiveAttack(randomNumber);
            if (!attackingKnight.getNextKnight().isDead()) {
                attackingKnight = attackingKnight.getNextKnight();
            } else {
                System.out.println(attackingKnight.getNextKnight() + " dies...");
                attackingKnight.setNextKnight(attackingKnight.getNextKnight().getNextKnight());
                attackingKnight = attackingKnight.getNextKnight();
            }
        }

        System.out.println(attackingKnight.getName() + " stands victorious!");
    }
}
